"""Argument validation for tool calls (Phase 2 Step 1).

A small, deterministic validator for a JSON-schema-like subset. It is
explicitly NOT a full JSON Schema implementation.

Supported schema keywords
---------------------------
Top level (must be ``type: "object"``):

* ``type``          -> ``"object"``
* ``properties``    -> dict of property name -> property schema
* ``required``      -> list of required property names
* ``additionalProperties`` -> bool (default True)

Property schemas support:

* ``type`` -> one of ``string`` / ``integer`` / ``number`` / ``boolean``
              / ``object`` / ``array``
* ``properties`` (for ``type: "object"``) -> nested object schema
* ``required`` (for ``type: "object"``) -> list of required property names
* ``additionalProperties`` (for ``type: "object"``) -> bool
* ``items`` (for ``type: "array"``) -> element schema

Unsupported keywords (``oneOf`` / ``anyOf`` / ``allOf`` / ``$ref`` /
``patternProperties`` / conditional schemas / ``format``) are NOT
silently ignored: if a schema uses one of them, validation raises a
``SchemaError`` so callers never mistakenly believe full JSON Schema is
supported.
"""

from __future__ import annotations

from typing import Any, Protocol

_PRIMITIVE_TYPES = frozenset(
    {"string", "integer", "number", "boolean", "object", "array"}
)

# Keywords this validator understands. Anything else is rejected so we
# never silently pretend to support full JSON Schema.
#
# ``title`` and ``description`` are metadata-only display keywords that
# do not affect validation logic; they are accepted (and ignored) so
# schemas auto-generated by MCP SDK / pydantic (which include ``title``)
# pass the compatibility gate. Structural keywords like ``oneOf`` /
# ``anyOf`` / ``allOf`` / ``$ref`` / ``$defs`` remain unsupported.
_SUPPORTED_TOP_KEYS = frozenset(
    {"type", "properties", "required", "additionalProperties", "title", "description"}
)
_SUPPORTED_PROP_KEYS = frozenset(
    {"type", "properties", "required", "additionalProperties", "items", "title", "description"}
)


class SchemaError(Exception):
    """Raised when a schema uses an unsupported keyword or malformed shape.

    This is a configuration / programmer error surfaced at validation
    time, distinct from a tool VALIDATION failure (which is about the
    arguments not matching a valid schema).
    """


class ToolArgumentValidator(Protocol):
    """Protocol for argument validators."""

    def validate(
        self,
        schema: dict[str, Any],
        arguments: dict[str, Any],
    ) -> dict[str, Any]:
        """Validate ``arguments`` against ``schema``.

        Returns the validated arguments on success; raises
        ``ValidationError`` if the arguments do not match the schema,
        or ``SchemaError`` if the schema itself is unsupported / malformed.
        """
        ...

    def validate_schema(self, schema: dict[str, Any]) -> None:
        """Check that ``schema`` is compatible with this validator.

        Raises ``SchemaError`` if the schema uses unsupported keywords or
        is malformed. Does NOT validate any arguments. Used by the MCP
        adapter to reject incompatible MCP tool schemas before
        registration rather than at first call.
        """
        ...


class ValidationError(Exception):
    """Raised when tool arguments do not match the schema."""

    def __init__(self, message: str, *, path: str = "") -> None:
        self.path = path
        super().__init__(f"{path}: {message}" if path else message)


def _check_schema_keys(schema: dict[str, Any], allowed: frozenset[str], where: str) -> None:
    unsupported = set(schema.keys()) - allowed
    if unsupported:
        raise SchemaError(
            f"{where}: unsupported schema keywords {sorted(unsupported)}; "
            f"this validator only supports {sorted(allowed)}"
        )


def _validate_value(schema: dict[str, Any], value: Any, path: str) -> None:
    """Recursively validate a value against a property schema."""
    if not isinstance(schema, dict):
        raise SchemaError(f"{path}: property schema must be a dict")
    _check_schema_keys(schema, _SUPPORTED_PROP_KEYS, path)

    declared_type = schema.get("type")
    if declared_type is None:
        # No type constraint -> accept any value (metadata-only property).
        return
    if not isinstance(declared_type, str) or declared_type not in _PRIMITIVE_TYPES:
        raise SchemaError(
            f"{path}: unsupported property type {declared_type!r}; "
            f"supported types are {sorted(_PRIMITIVE_TYPES)}"
        )

    if declared_type == "string":
        if not isinstance(value, str):
            raise ValidationError(f"expected string, got {type(value).__name__}", path=path)
    elif declared_type == "integer":
        # bool is a subclass of int in Python; reject it explicitly.
        if isinstance(value, bool) or not isinstance(value, int):
            raise ValidationError(f"expected integer, got {type(value).__name__}", path=path)
    elif declared_type == "number":
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValidationError(f"expected number, got {type(value).__name__}", path=path)
    elif declared_type == "boolean":
        if not isinstance(value, bool):
            raise ValidationError(f"expected boolean, got {type(value).__name__}", path=path)
    elif declared_type == "object":
        if not isinstance(value, dict):
            raise ValidationError(f"expected object, got {type(value).__name__}", path=path)
        _validate_object(schema, value, path)
    elif declared_type == "array":
        if not isinstance(value, list):
            raise ValidationError(f"expected array, got {type(value).__name__}", path=path)
        items_schema = schema.get("items")
        if items_schema is not None:
            for i, item in enumerate(value):
                _validate_value(items_schema, item, f"{path}[{i}]")


def _validate_object(
    schema: dict[str, Any], value: dict[str, Any], path: str
) -> None:
    """Validate an object value against an object-typed property schema."""
    properties = schema.get("properties", {})
    required = schema.get("required", [])
    additional = schema.get("additionalProperties", True)

    if not isinstance(properties, dict):
        raise SchemaError(f"{path}: 'properties' must be a dict")
    if not isinstance(required, list):
        raise SchemaError(f"{path}: 'required' must be a list")
    if not isinstance(additional, bool):
        raise SchemaError(f"{path}: 'additionalProperties' must be a bool")

    for req in required:
        if req not in value:
            raise ValidationError(f"missing required property {req!r}", path=path)

    for key, val in value.items():
        child_path = f"{path}.{key}" if path else key
        if key in properties:
            _validate_value(properties[key], val, child_path)
        else:
            if not additional:
                raise ValidationError(
                    f"unknown property {key!r} (additionalProperties is False)",
                    path=child_path,
                )


def _validate_schema_value(schema: dict[str, Any], path: str) -> None:
    """Recursively validate a property schema structure (no arguments).

    Used by ``SimpleToolArgumentValidator.validate_schema`` to check
    that a schema only uses supported keywords, without validating any
    arguments against it.
    """
    if not isinstance(schema, dict):
        raise SchemaError(f"{path}: property schema must be a dict")
    _check_schema_keys(schema, _SUPPORTED_PROP_KEYS, path)

    declared_type = schema.get("type")
    if declared_type is not None:
        if not isinstance(declared_type, str) or declared_type not in _PRIMITIVE_TYPES:
            raise SchemaError(
                f"{path}: unsupported property type {declared_type!r}; "
                f"supported types are {sorted(_PRIMITIVE_TYPES)}"
            )

    if declared_type == "object":
        properties = schema.get("properties", {})
        if not isinstance(properties, dict):
            raise SchemaError(f"{path}: 'properties' must be a dict")
        required = schema.get("required", [])
        if not isinstance(required, list):
            raise SchemaError(f"{path}: 'required' must be a list")
        additional = schema.get("additionalProperties", True)
        if not isinstance(additional, bool):
            raise SchemaError(f"{path}: 'additionalProperties' must be a bool")
        for child_name, child_schema in properties.items():
            _validate_schema_value(child_schema, f"{path}.{child_name}")
    elif declared_type == "array":
        items_schema = schema.get("items")
        if items_schema is not None:
            _validate_schema_value(items_schema, f"{path}[items]")


class SimpleToolArgumentValidator:
    """Deterministic validator for a small JSON-schema-like subset.

    See module docstring for the exact supported keywords. Unsupported
    schema keywords raise ``SchemaError`` rather than being silently
    ignored.
    """

    def validate(
        self,
        schema: dict[str, Any],
        arguments: dict[str, Any],
    ) -> dict[str, Any]:
        if not isinstance(schema, dict):
            raise SchemaError("schema must be a dict")
        if not isinstance(arguments, dict):
            raise ValidationError("arguments must be a dict")

        _check_schema_keys(schema, _SUPPORTED_TOP_KEYS, "<root>")

        declared_type = schema.get("type")
        if declared_type != "object":
            raise SchemaError(
                f"top-level schema type must be 'object', got {declared_type!r}"
            )

        _validate_object(schema, arguments, "")
        return arguments

    def validate_schema(self, schema: dict[str, Any]) -> None:
        """Check that ``schema`` is compatible with this validator.

        Recursively validates the schema structure (top-level and all
        nested property schemas) without validating any arguments.
        Raises ``SchemaError`` for unsupported keywords or malformed
        shapes. Used by the MCP adapter to reject incompatible schemas
        before tool registration.
        """
        if not isinstance(schema, dict):
            raise SchemaError("schema must be a dict")
        _check_schema_keys(schema, _SUPPORTED_TOP_KEYS, "<root>")
        declared_type = schema.get("type")
        if declared_type != "object":
            raise SchemaError(
                f"top-level schema type must be 'object', got {declared_type!r}"
            )
        properties = schema.get("properties", {})
        if not isinstance(properties, dict):
            raise SchemaError("<root>: 'properties' must be a dict")
        required = schema.get("required", [])
        if not isinstance(required, list):
            raise SchemaError("<root>: 'required' must be a list")
        additional = schema.get("additionalProperties", True)
        if not isinstance(additional, bool):
            raise SchemaError("<root>: 'additionalProperties' must be a bool")
        for prop_name, prop_schema in properties.items():
            _validate_schema_value(prop_schema, f"<root>.{prop_name}")
